services:
  master:
    image: mysql:8.0.36
    container_name: mysql-master
    restart: unless-stopped
    ports:
      - "3309:3306"
    volumes:
      - ./conf/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
      - ./data/master:/var/lib/mysql/
      - ./logs/master:/var/log/mysql/
#      - ./init-source.sql:/docker-entrypoint-initdb.d/init-source.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-12345678}
      REPLICATOR_USERNAME: ${REPLICATOR_USERNAME:-repl_user}
      REPLICATOR_PASSWORD: ${REPLICATOR_PASSWORD:-repl1234}
    networks:
      - mysql-network

  slave:
    image: mysql:8.0.36
    container_name: mysql-slave
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./conf/slave.cnf:/etc/mysql/conf.d/slave.cnf
      - ./init-slave.sh:/docker-entrypoint-initdb.d/init-slave.sh
      - ./data/slave:/var/lib/mysql/
      - ./logs/slave:/var/log/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-12345678}
      MYSQL_MASTER_HOST: ${MYSQL_MASTER_HOST:-master}
      REPLICATOR_USERNAME: ${REPLICATOR_USERNAME:-repl_user}
      REPLICATOR_PASSWORD: ${REPLICATOR_PASSWORD:-repl1234}
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge