mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "
  CHANGE MASTER TO
    MASTER_HOST='${MYSQL_MASTER_HOST}',
    MASTER_USER='${REPLICATOR_USERNAME}',
    MASTER_PASSWORD='${REPLICATOR_PASSWORD}',
    MASTER_LOG_FILE='mysql-bin.000001',
    MASTER_LOG_POS=0;

  START SLAVE;
"