mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "
CREATE USER '${REPLICATOR_USERNAME}'@'%' IDENTIFIED BY '${REPLICATOR_PASSWORD}';
GRANT REPLICATION SLAVE ON *.* TO '${REPLICATOR_USERNAME}'@'%';
FLUSH PRIVILEGES;
"